apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitoring
  labels:
    release: prometheus 
    role: alert-rules
spec:
  groups:
  - name: TestAlertGroup
    rules:
    - alert: EKSAutoHealerTest
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "This is a test alert to trigger the EKS auto-healer."
        description: "If you see this, the alert pipeline is working."