apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-web-app-monitor

  namespace: monitoring
  labels:

    release: my-monitoring-stack
spec:

  selector:
    matchLabels:
      app: my-web-app

  namespaceSelector:
    matchNames:
    - default

  endpoints:
  - port: http-metrics 
    path: /metrics     
    interval: 15s     